In [35]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" #the options for that are 'all', 'none', 'last' and 'last_expr'(the default is last_expr)

In [9]:
#Importing a package does not automatically import the submodules

# If you're wondering why it looks like sometimes you don't need those
# extra imports: some packages import some or all of their submodules
# when they are imported -- simply by doing those imports in their
# __init__.py files.

# Make sure the variable package is pointing to a package, not a
# module. Modules are files whereas packages are directories. All
# packages have the __path__ attribute (... unless someone deleted the
# attribute for some reason.)

import scipy # never do this for scipy
# because most of the functions in that top namespace are there for legacy reasons ONLY

# another rule of thumb:
# use scipy.linalg, not numpy.linalg : because scipy version is guranteed to be fast

print("* All ~submodules~ subpackages of package scipy")
#dir(scipy)

import pkgutil
import scipy
package = scipy
for importer, modulename, ispkg in pkgutil.walk_packages(path = package.__path__,
                                                      prefix = package.__name__+'.',
                                                      onerror = lambda x: None):
    #print(modulename)
    if ispkg:
        print(modulename)

* All ~submodules~ subpackages of package scipy
scipy._build_utils
scipy._lib
scipy._lib.tests
scipy.cluster
scipy.cluster.tests
scipy.constants
scipy.constants.tests
scipy.fftpack
scipy.fftpack.tests
scipy.integrate
scipy.integrate._ivp
scipy.integrate.tests
scipy.interpolate
scipy.interpolate.tests
scipy.io
scipy.io.arff
scipy.io.arff.tests
scipy.io.harwell_boeing
scipy.io.harwell_boeing.tests
scipy.io.matlab
scipy.io.matlab.tests
scipy.io.tests
scipy.linalg
scipy.linalg.tests
scipy.misc
scipy.misc.tests
scipy.ndimage
scipy.ndimage.tests
scipy.odr
scipy.odr.tests
scipy.optimize
scipy.optimize._lsq
scipy.optimize._shgo_lib
scipy.optimize._trlib
scipy.optimize._trustregion_constr
scipy.optimize._trustregion_constr.tests
scipy.optimize.tests
scipy.signal
scipy.signal.tests
scipy.signal.windows
scipy.sparse
scipy.sparse.csgraph
scipy.sparse.csgraph.tests
scipy.sparse.linalg
scipy.sparse.linalg.dsolve
scipy.sparse.linalg.dsolve.tests
scipy.sparse.linalg.eigen
scipy.sparse.linalg.eigen.arp

What Is Vector Quantization?

Strictly speaking, quantization is the procedure of approximating
continuous with discrete values; in practice, the input values to the
quantization procedure are often also discrete, but with a much finer
resolution than that of the output values. The goal of quantization
usually is to produce a more compact representation of the data while
maintaining its usefulness for a certain purpose. For example, to
store color intensities you can quantize floating-point values in the
range [0.0, 1.0] to integer values in the range 0-255, representing
them with 8 bits, which is considered a sufficient resolution for many
applications dealing with color. In this example, the spacing of
possible values is the same over the entire discrete set, so we speak
of uniform quantization; often, a nonuniform spacing is more
appropriate when better resolution is needed over some parts of the
range of values. Floating-point number representation is an example of
nonuniform quantization—you have the as many possible FP values
between 0.1 and 1 as you have between 10 and 100.

Both these are examples of scalar quantization—the input and output
values are scalars, or single numbers. You can do vector quantization
(VQ) too, replacing vectors from a continuous (or dense discrete)
input set with vectors from a much sparser set (note that here by
vector we mean an ordered set of N numbers, not just the special case
of points in 3D space). For example, if we have the colors of the
pixels in an image represented by triples of red, green, and blue
intensities in the [0.0, 1.0] range, we could quantize them uniformly
by quantizing each of the three intensities to an 8-bit number; this
leads us to the traditional 24-bit representation.

By quantizing each component of the vector for itself, we gain nothing
over standard scalar quantization; however, if we quantize the entire
vectors, replacing them with vectors from a carefully chosen sparse
nonuniform set and storing just indices into that set, we can get a
much more compact representation of the image. This is nothing but the
familiar paletted image representation. In VQ literature the
"palette," or the set of possible quantized values for the vectors is
called a "codebook," because you need it to "decode" the indices into
actual vector values.

In [15]:
import scipy.linalg
len(dir(scipy.linalg)) # lin algebra study index :)

139

In [55]:
import numpy as np
import matplotlib.pyplot as plt

#spio
from scipy import io as spio
d = np.ones((3, 3))
spio.savemat("savemat0.mat", {"d" : d}) #maybe .mat is Matlab related
#usecase, using matlab for matrix multiplication because of its better syntax

#svd skip for now mistake
d = np.ones((2, 3))
from scipy import linalg
u, s, vt = linalg.svd(d) #matrix singular value decomposition # mn: matrix factorization
# Singular value decomposition is a method of decomposing a matrix into three other matrices
u, s, vt
u.shape, s.shape, vt.shape
sd = np.diag(s)

#u.dot(sd).dot(vt)

from scipy.interpolate import interp1d
x = np.linspace(0, np.pi, 11)
x
y = np.sin(x) + np.random.rand()


(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([2.44948974e+00, 1.11022302e-16]),
 array([[-0.57735027, -0.57735027, -0.57735027],
        [-0.81649658,  0.40824829,  0.40824829],
        [ 0.        , -0.70710678,  0.70710678]]))

((2, 2), (2,), (3, 3))

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265])